version: "3.9"
services:
  api:
    image: nsioay/backend:latest
    ports:
      - "80:80"
    env_file: ./.env
    environment:
      - AWSConfig__AWSAccessKey=$AWSConfig__AWSAccessKey
      - AWSConfig__AWSSecretKey=$AWSConfig__AWSSecretKey
      - AWSConfig__BucketName=$AWSConfig__BucketName
      - ClientOrigin=$ClientOrigin
      - ConnectionStrings__StudentManagementConnection=$ConnectionStrings__StudentManagementConnection
      - ConnectionStrings__IdentityConnection=$ConnectionStrings__IdentityConnection
